# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/rolland/Documents/GIT/A-Eye/A-Eye_FPGA/vivado_project/conv_v2/conv_v2.srcs/sources_1/bd/design_1/ip/design_1_axi_mm2s_mapper_2_1/design_1_axi_mm2s_mapper_2_1.xci
# IP: The module: 'design_1_axi_mm2s_mapper_2_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rolland/Documents/GIT/A-Eye/A-Eye_FPGA/vivado_project/conv_v2/conv_v2.gen/sources_1/bd/design_1/ip/design_1_axi_mm2s_mapper_2_1/design_1_axi_mm2s_mapper_2_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_mm2s_mapper_2_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/rolland/Documents/GIT/A-Eye/A-Eye_FPGA/vivado_project/conv_v2/conv_v2.srcs/sources_1/bd/design_1/ip/design_1_axi_mm2s_mapper_2_1/design_1_axi_mm2s_mapper_2_1.xci
# IP: The module: 'design_1_axi_mm2s_mapper_2_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rolland/Documents/GIT/A-Eye/A-Eye_FPGA/vivado_project/conv_v2/conv_v2.gen/sources_1/bd/design_1/ip/design_1_axi_mm2s_mapper_2_1/design_1_axi_mm2s_mapper_2_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_mm2s_mapper_2_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
