# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/rolland/Documents/GIT/A-Eye/A-Eye_FPGA/vivado/conv_gpio/conv_gpio.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_6/design_1_axi_gpio_0_6.xci
# IP: The module: 'design_1_axi_gpio_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rolland/Documents/GIT/A-Eye/A-Eye_FPGA/vivado/conv_gpio/conv_gpio.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_6/design_1_axi_gpio_0_6_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/rolland/Documents/GIT/A-Eye/A-Eye_FPGA/vivado/conv_gpio/conv_gpio.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_6/design_1_axi_gpio_0_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/rolland/Documents/GIT/A-Eye/A-Eye_FPGA/vivado/conv_gpio/conv_gpio.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_6/design_1_axi_gpio_0_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/rolland/Documents/GIT/A-Eye/A-Eye_FPGA/vivado/conv_gpio/conv_gpio.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_6/design_1_axi_gpio_0_6.xci
# IP: The module: 'design_1_axi_gpio_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rolland/Documents/GIT/A-Eye/A-Eye_FPGA/vivado/conv_gpio/conv_gpio.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_6/design_1_axi_gpio_0_6_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/rolland/Documents/GIT/A-Eye/A-Eye_FPGA/vivado/conv_gpio/conv_gpio.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_6/design_1_axi_gpio_0_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/rolland/Documents/GIT/A-Eye/A-Eye_FPGA/vivado/conv_gpio/conv_gpio.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_6/design_1_axi_gpio_0_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
