@startsalt arbo_zybo

{
    {T
        +A-Eye_root
            ++A-Eye_Communication
                +++build
                +++src
                    ++++TM
                        +++++encodageTM.c
                        +++++encodageTM.h
                    ++++TC
                        +++++decodageTC.c
                        +++++decodageTC.h
                    ++++Server 
                        +++++tcp_server.h
                    ++++Interpreteur
                        +++++interpreteur.c
                        +++++interpreteur.h
                        +++++Circular_buffer
                            ++++++Circular_buffer.c
                            ++++++Circular_buffer.h
                        ++++struct_allocation.h
                    ++++tcp_server.cpp
            ++A-Eye_Visor
                +++build
                +++src
                    ++++json
                        +++++json.cpp
                        +++++json.hpp
                    ++++preprocess
                        +++++preprocess.cpp
                        +++++preprocess.hpp
                    ++++AI.cpp
                +++weights.json
            ++demo.sh
            ++get_rand_img.py
            ++IAtoINT (pipe)
            ++README.md
            ++temp.csv
            ++temp.bmp
        +airbus_train_bmp
            ++pas_bateau
            ++bateau
    }
}

@endsalt

@startsalt arbo_PC
{
    {T
    +A-Eye_Controller
        ++A-Eye_Controller
            +++A-Eye_Communication
                ++++client.py
                ++++encodageTC.py
                ++++decodagetTM.py
                ++++localCom.py
            +++StockagePC
                ++++arborescence.py
                ++++naming.py
                ++++stockage.py
                ++++run_stockage.py
                ++++test.py
                ++++README.md
            +++SpecFlowProject1
                ++++Features
                    +++++Connection.feature
                    +++++Interaction.feature   
                ++++StepsDefinitions
                    +++++ConnectionStepDefinition
                    +++++InteractionStepDefinition
            +++Tests
                ++++features
                    +++++A-Eye_root.feature 
                ++++steps
                    +++++steps.py           
            +++config.json
            +++last_config.json
            +++ConfigFile.cs
            +++Controller.cs
            +++Controller.Designer.cs
            +++Program.cs
            +++SubProcess.cs
            +++[OUTPUT_FOLDER]/Images
                ++++Année
                    +++++Mois
                        ++++++Jour
                            +++++++Auto
                                ++++++++A_*annee*_*mois*_*jour*_*heure_*idx*.bmp
                            +++++++Manual
                                ++++++++M_*annee*_*mois*_*jour*_*heure*_*idx*.bmp
        ++A-Eye_Controller.sln
        ++README.md
    }
}

@endsalt