# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/A-Eye/A-Eye_FPGA/vivado/conv_v3/conv_v3.srcs/sources_1/ip/axis_data_fifo_0/axis_data_fifo_0.xci
# IP: The module: 'axis_data_fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/A-Eye/A-Eye_FPGA/vivado/conv_v3/conv_v3.gen/sources_1/ip/axis_data_fifo_0/axis_data_fifo_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_data_fifo_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/A-Eye/A-Eye_FPGA/vivado/conv_v3/conv_v3.srcs/sources_1/ip/axis_data_fifo_0/axis_data_fifo_0.xci
# IP: The module: 'axis_data_fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/A-Eye/A-Eye_FPGA/vivado/conv_v3/conv_v3.gen/sources_1/ip/axis_data_fifo_0/axis_data_fifo_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_data_fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
